steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/influence/influence-services:$COMMIT_SHA'
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/influence/influence-services:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - influence-services
      - --image=$_REGION-docker.pkg.dev/$_PROJECT_ID/influence/influence-services:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated

substitutions:
  _REGION: europe-west9
  _PROJECT_ID: influence-beymedias

options:
    logging: CLOUD_LOGGING_ONLY